// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000121Component } from './my.000121.component';

@NgModule({
  declarations: [
    My000121Component,
  ],
  imports: [CommonModule],
  exports: [
    My000121Component,
  ]
})
export class Module000071 { }
