// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000177Component } from './my.000177.component';

@NgModule({
  declarations: [
    My000177Component,
  ],
  imports: [CommonModule],
  exports: [
    My000177Component,
  ]
})
export class Module000127 { }
