// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000125Component } from './my.000125.component';

@NgModule({
  declarations: [
    My000125Component,
  ],
  imports: [CommonModule],
  exports: [
    My000125Component,
  ]
})
export class Module000075 { }
