// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000181Component } from './my.000181.component';

@NgModule({
  declarations: [
    My000181Component,
  ],
  imports: [CommonModule],
  exports: [
    My000181Component,
  ]
})
export class Module000131 { }
