// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000119Component } from './my.000119.component';

@NgModule({
  declarations: [
    My000119Component,
  ],
  imports: [CommonModule],
  exports: [
    My000119Component,
  ]
})
export class Module000069 { }
