// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000193Component } from './my.000193.component';

@NgModule({
  declarations: [
    My000193Component,
  ],
  imports: [CommonModule],
  exports: [
    My000193Component,
  ]
})
export class Module000143 { }
