// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000167Component } from './my.000167.component';

@NgModule({
  declarations: [
    My000167Component,
  ],
  imports: [CommonModule],
  exports: [
    My000167Component,
  ]
})
export class Module000117 { }
