// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000164Component } from './my.000164.component';

@NgModule({
  declarations: [
    My000164Component,
  ],
  imports: [CommonModule],
  exports: [
    My000164Component,
  ]
})
export class Module000114 { }
