// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000154Component } from './my.000154.component';

@NgModule({
  declarations: [
    My000154Component,
  ],
  imports: [CommonModule],
  exports: [
    My000154Component,
  ]
})
export class Module000104 { }
