// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000179Component } from './my.000179.component';

@NgModule({
  declarations: [
    My000179Component,
  ],
  imports: [CommonModule],
  exports: [
    My000179Component,
  ]
})
export class Module000129 { }
