// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000157Component } from './my.000157.component';

@NgModule({
  declarations: [
    My000157Component,
  ],
  imports: [CommonModule],
  exports: [
    My000157Component,
  ]
})
export class Module000107 { }
