// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000186Component } from './my.000186.component';

@NgModule({
  declarations: [
    My000186Component,
  ],
  imports: [CommonModule],
  exports: [
    My000186Component,
  ]
})
export class Module000136 { }
