// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000134Component } from './my.000134.component';

@NgModule({
  declarations: [
    My000134Component,
  ],
  imports: [CommonModule],
  exports: [
    My000134Component,
  ]
})
export class Module000084 { }
