// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000162Component } from './my.000162.component';

@NgModule({
  declarations: [
    My000162Component,
  ],
  imports: [CommonModule],
  exports: [
    My000162Component,
  ]
})
export class Module000112 { }
