// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000190Component } from './my.000190.component';

@NgModule({
  declarations: [
    My000190Component,
  ],
  imports: [CommonModule],
  exports: [
    My000190Component,
  ]
})
export class Module000140 { }
