// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000069Component } from './my.000069.component';
import { My000070Component } from './my.000070.component';

@NgModule({
  declarations: [
    My000069Component,
    My000070Component,
  ],
  imports: [CommonModule],
  exports: [
    My000069Component,
  ]
})
export class Module000034 { }
