// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000183Component } from './my.000183.component';

@NgModule({
  declarations: [
    My000183Component,
  ],
  imports: [CommonModule],
  exports: [
    My000183Component,
  ]
})
export class Module000133 { }
