// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000146Component } from './my.000146.component';

@NgModule({
  declarations: [
    My000146Component,
  ],
  imports: [CommonModule],
  exports: [
    My000146Component,
  ]
})
export class Module000096 { }
