// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000087Component } from './my.000087.component';
import { My000088Component } from './my.000088.component';

@NgModule({
  declarations: [
    My000087Component,
    My000088Component,
  ],
  imports: [CommonModule],
  exports: [
    My000087Component,
  ]
})
export class Module000043 { }
