// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000151Component } from './my.000151.component';

@NgModule({
  declarations: [
    My000151Component,
  ],
  imports: [CommonModule],
  exports: [
    My000151Component,
  ]
})
export class Module000101 { }
