// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000145Component } from './my.000145.component';

@NgModule({
  declarations: [
    My000145Component,
  ],
  imports: [CommonModule],
  exports: [
    My000145Component,
  ]
})
export class Module000095 { }
