// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000171Component } from './my.000171.component';

@NgModule({
  declarations: [
    My000171Component,
  ],
  imports: [CommonModule],
  exports: [
    My000171Component,
  ]
})
export class Module000121 { }
