// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000017Component } from './my.000017.component';
import { My000018Component } from './my.000018.component';

@NgModule({
  declarations: [
    My000017Component,
    My000018Component,
  ],
  imports: [CommonModule],
  exports: [
    My000017Component,
  ]
})
export class Module000008 { }
