// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000184Component } from './my.000184.component';

@NgModule({
  declarations: [
    My000184Component,
  ],
  imports: [CommonModule],
  exports: [
    My000184Component,
  ]
})
export class Module000134 { }
