// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000192Component } from './my.000192.component';

@NgModule({
  declarations: [
    My000192Component,
  ],
  imports: [CommonModule],
  exports: [
    My000192Component,
  ]
})
export class Module000142 { }
