// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000199Component } from './my.000199.component';

@NgModule({
  declarations: [
    My000199Component,
  ],
  imports: [CommonModule],
  exports: [
    My000199Component,
  ]
})
export class Module000149 { }
