// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000135Component } from './my.000135.component';

@NgModule({
  declarations: [
    My000135Component,
  ],
  imports: [CommonModule],
  exports: [
    My000135Component,
  ]
})
export class Module000085 { }
