// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000155Component } from './my.000155.component';

@NgModule({
  declarations: [
    My000155Component,
  ],
  imports: [CommonModule],
  exports: [
    My000155Component,
  ]
})
export class Module000105 { }
