// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000033Component } from './my.000033.component';
import { My000034Component } from './my.000034.component';

@NgModule({
  declarations: [
    My000033Component,
    My000034Component,
  ],
  imports: [CommonModule],
  exports: [
    My000033Component,
  ]
})
export class Module000016 { }
