// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000061Component } from './my.000061.component';
import { My000062Component } from './my.000062.component';

@NgModule({
  declarations: [
    My000061Component,
    My000062Component,
  ],
  imports: [CommonModule],
  exports: [
    My000061Component,
  ]
})
export class Module000030 { }
