// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000178Component } from './my.000178.component';

@NgModule({
  declarations: [
    My000178Component,
  ],
  imports: [CommonModule],
  exports: [
    My000178Component,
  ]
})
export class Module000128 { }
