// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000093Component } from './my.000093.component';
import { My000094Component } from './my.000094.component';

@NgModule({
  declarations: [
    My000093Component,
    My000094Component,
  ],
  imports: [CommonModule],
  exports: [
    My000093Component,
  ]
})
export class Module000046 { }
