// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000053Component } from './my.000053.component';
import { My000054Component } from './my.000054.component';

@NgModule({
  declarations: [
    My000053Component,
    My000054Component,
  ],
  imports: [CommonModule],
  exports: [
    My000053Component,
  ]
})
export class Module000026 { }
