// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000174Component } from './my.000174.component';

@NgModule({
  declarations: [
    My000174Component,
  ],
  imports: [CommonModule],
  exports: [
    My000174Component,
  ]
})
export class Module000124 { }
