// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000156Component } from './my.000156.component';

@NgModule({
  declarations: [
    My000156Component,
  ],
  imports: [CommonModule],
  exports: [
    My000156Component,
  ]
})
export class Module000106 { }
