// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000029Component } from './my.000029.component';
import { My000030Component } from './my.000030.component';

@NgModule({
  declarations: [
    My000029Component,
    My000030Component,
  ],
  imports: [CommonModule],
  exports: [
    My000029Component,
  ]
})
export class Module000014 { }
