// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000085Component } from './my.000085.component';
import { My000086Component } from './my.000086.component';

@NgModule({
  declarations: [
    My000085Component,
    My000086Component,
  ],
  imports: [CommonModule],
  exports: [
    My000085Component,
  ]
})
export class Module000042 { }
