// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000175Component } from './my.000175.component';

@NgModule({
  declarations: [
    My000175Component,
  ],
  imports: [CommonModule],
  exports: [
    My000175Component,
  ]
})
export class Module000125 { }
