// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000138Component } from './my.000138.component';

@NgModule({
  declarations: [
    My000138Component,
  ],
  imports: [CommonModule],
  exports: [
    My000138Component,
  ]
})
export class Module000088 { }
