// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000172Component } from './my.000172.component';

@NgModule({
  declarations: [
    My000172Component,
  ],
  imports: [CommonModule],
  exports: [
    My000172Component,
  ]
})
export class Module000122 { }
