// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000195Component } from './my.000195.component';

@NgModule({
  declarations: [
    My000195Component,
  ],
  imports: [CommonModule],
  exports: [
    My000195Component,
  ]
})
export class Module000145 { }
