// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000139Component } from './my.000139.component';

@NgModule({
  declarations: [
    My000139Component,
  ],
  imports: [CommonModule],
  exports: [
    My000139Component,
  ]
})
export class Module000089 { }
