// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000065Component } from './my.000065.component';
import { My000066Component } from './my.000066.component';

@NgModule({
  declarations: [
    My000065Component,
    My000066Component,
  ],
  imports: [CommonModule],
  exports: [
    My000065Component,
  ]
})
export class Module000032 { }
