// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000182Component } from './my.000182.component';

@NgModule({
  declarations: [
    My000182Component,
  ],
  imports: [CommonModule],
  exports: [
    My000182Component,
  ]
})
export class Module000132 { }
