// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000143Component } from './my.000143.component';

@NgModule({
  declarations: [
    My000143Component,
  ],
  imports: [CommonModule],
  exports: [
    My000143Component,
  ]
})
export class Module000093 { }
