// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000132Component } from './my.000132.component';

@NgModule({
  declarations: [
    My000132Component,
  ],
  imports: [CommonModule],
  exports: [
    My000132Component,
  ]
})
export class Module000082 { }
