// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000187Component } from './my.000187.component';

@NgModule({
  declarations: [
    My000187Component,
  ],
  imports: [CommonModule],
  exports: [
    My000187Component,
  ]
})
export class Module000137 { }
