// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000196Component } from './my.000196.component';

@NgModule({
  declarations: [
    My000196Component,
  ],
  imports: [CommonModule],
  exports: [
    My000196Component,
  ]
})
export class Module000146 { }
