// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000147Component } from './my.000147.component';

@NgModule({
  declarations: [
    My000147Component,
  ],
  imports: [CommonModule],
  exports: [
    My000147Component,
  ]
})
export class Module000097 { }
