// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { BrowserModule  } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import { Module000000 } from './Module000000/Module000000.module';
import { Module000001 } from './Module000001/Module000001.module';
import { Module000002 } from './Module000002/Module000002.module';
import { Module000003 } from './Module000003/Module000003.module';
import { Module000004 } from './Module000004/Module000004.module';
import { Module000005 } from './Module000005/Module000005.module';
import { Module000006 } from './Module000006/Module000006.module';
import { Module000007 } from './Module000007/Module000007.module';
import { Module000008 } from './Module000008/Module000008.module';
import { Module000009 } from './Module000009/Module000009.module';
import { Module000010 } from './Module000010/Module000010.module';
import { Module000011 } from './Module000011/Module000011.module';
import { Module000012 } from './Module000012/Module000012.module';
import { Module000013 } from './Module000013/Module000013.module';
import { Module000014 } from './Module000014/Module000014.module';
import { Module000015 } from './Module000015/Module000015.module';
import { Module000016 } from './Module000016/Module000016.module';
import { Module000017 } from './Module000017/Module000017.module';
import { Module000018 } from './Module000018/Module000018.module';
import { Module000019 } from './Module000019/Module000019.module';
import { Module000020 } from './Module000020/Module000020.module';
import { Module000021 } from './Module000021/Module000021.module';
import { Module000022 } from './Module000022/Module000022.module';
import { Module000023 } from './Module000023/Module000023.module';
import { Module000024 } from './Module000024/Module000024.module';
import { Module000025 } from './Module000025/Module000025.module';
import { Module000026 } from './Module000026/Module000026.module';
import { Module000027 } from './Module000027/Module000027.module';
import { Module000028 } from './Module000028/Module000028.module';
import { Module000029 } from './Module000029/Module000029.module';
import { Module000030 } from './Module000030/Module000030.module';
import { Module000031 } from './Module000031/Module000031.module';
import { Module000032 } from './Module000032/Module000032.module';
import { Module000033 } from './Module000033/Module000033.module';
import { Module000034 } from './Module000034/Module000034.module';
import { Module000035 } from './Module000035/Module000035.module';
import { Module000036 } from './Module000036/Module000036.module';
import { Module000037 } from './Module000037/Module000037.module';
import { Module000038 } from './Module000038/Module000038.module';
import { Module000039 } from './Module000039/Module000039.module';
import { Module000040 } from './Module000040/Module000040.module';
import { Module000041 } from './Module000041/Module000041.module';
import { Module000042 } from './Module000042/Module000042.module';
import { Module000043 } from './Module000043/Module000043.module';
import { Module000044 } from './Module000044/Module000044.module';
import { Module000045 } from './Module000045/Module000045.module';
import { Module000046 } from './Module000046/Module000046.module';
import { Module000047 } from './Module000047/Module000047.module';
import { Module000048 } from './Module000048/Module000048.module';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    Module000000,
    Module000001,
    Module000002,
    Module000003,
    Module000004,
    Module000005,
    Module000006,
    Module000007,
    Module000008,
    Module000009,
    Module000010,
    Module000011,
    Module000012,
    Module000013,
    Module000014,
    Module000015,
    Module000016,
    Module000017,
    Module000018,
    Module000019,
    Module000020,
    Module000021,
    Module000022,
    Module000023,
    Module000024,
    Module000025,
    Module000026,
    Module000027,
    Module000028,
    Module000029,
    Module000030,
    Module000031,
    Module000032,
    Module000033,
    Module000034,
    Module000035,
    Module000036,
    Module000037,
    Module000038,
    Module000039,
    Module000040,
    Module000041,
    Module000042,
    Module000043,
    Module000044,
    Module000045,
    Module000046,
    Module000047,
    Module000048,
],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }
