// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000133Component } from './my.000133.component';

@NgModule({
  declarations: [
    My000133Component,
  ],
  imports: [CommonModule],
  exports: [
    My000133Component,
  ]
})
export class Module000083 { }
