// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000055Component } from './my.000055.component';
import { My000056Component } from './my.000056.component';

@NgModule({
  declarations: [
    My000055Component,
    My000056Component,
  ],
  imports: [CommonModule],
  exports: [
    My000055Component,
  ]
})
export class Module000027 { }
