// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000057Component } from './my.000057.component';
import { My000058Component } from './my.000058.component';

@NgModule({
  declarations: [
    My000057Component,
    My000058Component,
  ],
  imports: [CommonModule],
  exports: [
    My000057Component,
  ]
})
export class Module000028 { }
