// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000130Component } from './my.000130.component';

@NgModule({
  declarations: [
    My000130Component,
  ],
  imports: [CommonModule],
  exports: [
    My000130Component,
  ]
})
export class Module000080 { }
