// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000031Component } from './my.000031.component';
import { My000032Component } from './my.000032.component';

@NgModule({
  declarations: [
    My000031Component,
    My000032Component,
  ],
  imports: [CommonModule],
  exports: [
    My000031Component,
  ]
})
export class Module000015 { }
