// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000180Component } from './my.000180.component';

@NgModule({
  declarations: [
    My000180Component,
  ],
  imports: [CommonModule],
  exports: [
    My000180Component,
  ]
})
export class Module000130 { }
