// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000142Component } from './my.000142.component';

@NgModule({
  declarations: [
    My000142Component,
  ],
  imports: [CommonModule],
  exports: [
    My000142Component,
  ]
})
export class Module000092 { }
