// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000194Component } from './my.000194.component';

@NgModule({
  declarations: [
    My000194Component,
  ],
  imports: [CommonModule],
  exports: [
    My000194Component,
  ]
})
export class Module000144 { }
