// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000198Component } from './my.000198.component';

@NgModule({
  declarations: [
    My000198Component,
  ],
  imports: [CommonModule],
  exports: [
    My000198Component,
  ]
})
export class Module000148 { }
