// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000169Component } from './my.000169.component';

@NgModule({
  declarations: [
    My000169Component,
  ],
  imports: [CommonModule],
  exports: [
    My000169Component,
  ]
})
export class Module000119 { }
