// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000011Component } from './my.000011.component';
import { My000012Component } from './my.000012.component';

@NgModule({
  declarations: [
    My000011Component,
    My000012Component,
  ],
  imports: [CommonModule],
  exports: [
    My000011Component,
  ]
})
export class Module000005 { }
