// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000170Component } from './my.000170.component';

@NgModule({
  declarations: [
    My000170Component,
  ],
  imports: [CommonModule],
  exports: [
    My000170Component,
  ]
})
export class Module000120 { }
