// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000005Component } from './my.000005.component';
import { My000006Component } from './my.000006.component';

@NgModule({
  declarations: [
    My000005Component,
    My000006Component,
  ],
  imports: [CommonModule],
  exports: [
    My000005Component,
  ]
})
export class Module000002 { }
