// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000159Component } from './my.000159.component';

@NgModule({
  declarations: [
    My000159Component,
  ],
  imports: [CommonModule],
  exports: [
    My000159Component,
  ]
})
export class Module000109 { }
