// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000120Component } from './my.000120.component';

@NgModule({
  declarations: [
    My000120Component,
  ],
  imports: [CommonModule],
  exports: [
    My000120Component,
  ]
})
export class Module000070 { }
