// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000141Component } from './my.000141.component';

@NgModule({
  declarations: [
    My000141Component,
  ],
  imports: [CommonModule],
  exports: [
    My000141Component,
  ]
})
export class Module000091 { }
