// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000131Component } from './my.000131.component';

@NgModule({
  declarations: [
    My000131Component,
  ],
  imports: [CommonModule],
  exports: [
    My000131Component,
  ]
})
export class Module000081 { }
