// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000165Component } from './my.000165.component';

@NgModule({
  declarations: [
    My000165Component,
  ],
  imports: [CommonModule],
  exports: [
    My000165Component,
  ]
})
export class Module000115 { }
