// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000161Component } from './my.000161.component';

@NgModule({
  declarations: [
    My000161Component,
  ],
  imports: [CommonModule],
  exports: [
    My000161Component,
  ]
})
export class Module000111 { }
