// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000197Component } from './my.000197.component';

@NgModule({
  declarations: [
    My000197Component,
  ],
  imports: [CommonModule],
  exports: [
    My000197Component,
  ]
})
export class Module000147 { }
