// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000045Component } from './my.000045.component';
import { My000046Component } from './my.000046.component';

@NgModule({
  declarations: [
    My000045Component,
    My000046Component,
  ],
  imports: [CommonModule],
  exports: [
    My000045Component,
  ]
})
export class Module000022 { }
