// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000077Component } from './my.000077.component';
import { My000078Component } from './my.000078.component';

@NgModule({
  declarations: [
    My000077Component,
    My000078Component,
  ],
  imports: [CommonModule],
  exports: [
    My000077Component,
  ]
})
export class Module000038 { }
