// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000150Component } from './my.000150.component';

@NgModule({
  declarations: [
    My000150Component,
  ],
  imports: [CommonModule],
  exports: [
    My000150Component,
  ]
})
export class Module000100 { }
