// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000149Component } from './my.000149.component';

@NgModule({
  declarations: [
    My000149Component,
  ],
  imports: [CommonModule],
  exports: [
    My000149Component,
  ]
})
export class Module000099 { }
