// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000166Component } from './my.000166.component';

@NgModule({
  declarations: [
    My000166Component,
  ],
  imports: [CommonModule],
  exports: [
    My000166Component,
  ]
})
export class Module000116 { }
