// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000173Component } from './my.000173.component';

@NgModule({
  declarations: [
    My000173Component,
  ],
  imports: [CommonModule],
  exports: [
    My000173Component,
  ]
})
export class Module000123 { }
