// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000015Component } from './my.000015.component';
import { My000016Component } from './my.000016.component';

@NgModule({
  declarations: [
    My000015Component,
    My000016Component,
  ],
  imports: [CommonModule],
  exports: [
    My000015Component,
  ]
})
export class Module000007 { }
