// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000126Component } from './my.000126.component';

@NgModule({
  declarations: [
    My000126Component,
  ],
  imports: [CommonModule],
  exports: [
    My000126Component,
  ]
})
export class Module000076 { }
