// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000136Component } from './my.000136.component';

@NgModule({
  declarations: [
    My000136Component,
  ],
  imports: [CommonModule],
  exports: [
    My000136Component,
  ]
})
export class Module000086 { }
