// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000144Component } from './my.000144.component';

@NgModule({
  declarations: [
    My000144Component,
  ],
  imports: [CommonModule],
  exports: [
    My000144Component,
  ]
})
export class Module000094 { }
